apiVersion: v1
kind: Service
metadata:
  name: quivitech-im-staging-service
  namespace: quivitech-im-stag
  labels:
    app: quivitech-im
spec:
  type: ClusterIP
  selector:
    app: quivitech-im
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
